"""This script converts Jupyter notebooks in the demo/ folder to Markdown docs and regenerates the llms.txt files.

The API reference is auto-generated by mkdocstrings — see mkdocs.yml and
docs/reference/api.md. To build or serve the full documentation site run:

    poetry run mkdocs build     # build static HTML into site/
    poetry run mkdocs serve     # serve with live-reload at http://127.0.0.1:8000

Running ``python make_docs.py`` will:

1. Convert every notebook in ``demo/`` into the matching ``docs/*.md`` file.
2. Regenerate ``llms.txt`` (site map for LLM consumers, per the llms.txt spec).
3. Regenerate ``llms-full.txt`` (single-file concatenation of every doc).
"""

import os
from pathlib import Path

import nbformat
from bs4 import BeautifulSoup
from nbconvert import MarkdownExporter

REPO_ROOT = Path(__file__).parent
DOCS_ROOT = REPO_ROOT / "docs"
GITHUB_DOCS_BASE = "https://github.com/tonyfujs/pymetadataeditor/blob/DEV/docs"

LLMS_TXT_INTRO = (
    "# pyMetadataEditor\n"
    "\n"
    "> Python client library for the [Metadata Editor](https://github.com/mah0001/metadata-editor)"
    " REST API. It lets data curators create, retrieve, update, and manage structured metadata"
    " for research datasets across ten data types (microdata, indicators, indicators_db,"
    " geospatial, documents, scripts, images, videos, tables, resources), with LLM-powered"
    " automatic metadata generation, admin-metadata CRUD, user lookup, and collection"
    " permission management.\n"
    "\n"
    "The public API is a single class, ``MetadataEditor`` (from ``pymetadataeditor``), that"
    ' wraps the REST API. Every metadata method accepts an ``output_mode`` of ``"dict"``,'
    ' ``"pydantic"``, or ``"excel"``. Errors raised against the Metadata Editor API are'
    " translated into a semantic exception hierarchy rooted at ``MetadataEditorAPIError``"
    " (itself a subclass of ``requests.exceptions.HTTPError``).\n"
    "\n"
    "Start with the getting-started guide and the agent skill, then dive into user-guide"
    " topics as needed. The API reference page is auto-generated from source docstrings by"
    " mkdocstrings and is always current.\n"
)

# (H2 section title, [(relative doc path, one-line description), ...])
LLMS_TXT_SECTIONS: list[tuple[str, list[tuple[str, str]]]] = [
    (
        "Start here",
        [
            ("index.md", "Site landing page — overview of capabilities and supported metadata types."),
            ("getting_started.md", "End-to-end first workflow: connect, browse, retrieve, and update a project."),
            ("skill.md", "Agent skill: architecture, capability map, common workflows, and key conventions."),
            ("ai_and_llms.md", "AI & LLMs overview: how to use the skill, llms.txt, and llms-full.txt."),
        ],
    ),
    (
        "User guide",
        [
            ("user_guide/01_browsing_projects.md", "List, filter, and discover existing projects."),
            ("user_guide/02_schemas_and_templates.md", "Templates, schemas, and how they drive field validation."),
            ("user_guide/03_creating_metadata.md", "Build and upload new project metadata."),
            ("user_guide/04_retrieving_metadata.md", "Download a project in dict, Pydantic, or Excel form."),
            ("user_guide/05_updating_metadata.md", "Full-replace updates and single-op JSON Patch edits."),
            ("user_guide/06_working_with_formats.md", "Round-trip metadata between dict, Pydantic, and Excel."),
            ("user_guide/07_ai_powered_generation.md", "Draft or augment metadata from source files with an LLM."),
            ("user_guide/08_managing_collections.md", "Create, list, copy, move, and populate collections."),
            ("user_guide/09_managing_resources.md", "Attach and update file resources on a project."),
            ("user_guide/10_deleting_data.md", "Safe deletion of projects, collections, templates, resources."),
            ("user_guide/11_advanced.md", "Lower-level access and edge-case patterns."),
            ("user_guide/12_managing_admin_metadata.md", "Admin metadata CRUD keyed by (project_id, template_uid)."),
            (
                "user_guide/13_users_and_permissions.md",
                "Look up users and manage project-access + ACL permissions on collections.",
            ),
        ],
    ),
    (
        "How-to recipes",
        [
            ("how_to/move_projects_between_collections.md", "Bulk-move projects between collections."),
            ("how_to/batch_upload_from_excel.md", "Ingest a spreadsheet of records as new projects."),
            ("how_to/instance_to_instance_migration.md", "Copy projects between two Metadata Editor instances."),
        ],
    ),
    (
        "Reference",
        [
            ("reference/api.md", "Full method signatures and docstrings (mkdocstrings-generated)."),
            ("reference/output_modes.md", "dict / pydantic / excel output modes and their aliases."),
            ("reference/metadata_types.md", "Supported metadata types and the internal API aliases."),
            ("reference/error_handling.md", "Exception hierarchy, status-code mapping, handling patterns."),
        ],
    ),
    (
        "Developer reference",
        [
            ("developer/architecture.md", "Package internals, module responsibilities, and data flow."),
            ("developer/modules/interface.md", "Every public MetadataEditor method, signature, and example."),
            ("developer/modules/requester.md", "HTTP layer, auth, SSL, and exception translation."),
            ("developer/modules/templates.md", "Template-to-Pydantic conversion and constraint handling."),
            ("developer/modules/llm_helpers.md", "LLM call orchestration, file conversion, validation."),
            ("developer/modules/utils.md", "JSON Patch validation, empty-value cleaning, rule stripping."),
        ],
    ),
    (
        "Schema reference",
        [
            ("reference/schemas/document.md", "`document` metadata type."),
            ("reference/schemas/geospatial.md", "`geospatial` metadata type."),
            ("reference/schemas/image.md", "`image` metadata type."),
            ("reference/schemas/indicator.md", "`indicator` (time series) metadata type."),
            ("reference/schemas/indicators_db.md", "`indicators_db` (indicator database) metadata type."),
            ("reference/schemas/microdata.md", "`microdata` (survey) metadata type."),
            ("reference/schemas/resource.md", "`resource` (file attachment) metadata type."),
            ("reference/schemas/script.md", "`script` metadata type."),
            ("reference/schemas/table.md", "`table` metadata type."),
            ("reference/schemas/video.md", "`video` metadata type."),
        ],
    ),
    (
        "Optional",
        [
            ("examples.md", "Worked examples: batch upload, collection migration, instance-to-instance transfer."),
            ("using_automated_metadata_creation.md", "Long-form LLM-powered metadata generation guide."),
            ("demo.md", "End-to-end notebook demonstration (converted from `demo/demo.ipynb`)."),
        ],
    ),
]

# Order of files included in llms-full.txt (deduplicated — we use developer/modules over modules).
LLMS_FULL_ORDER: list[str] = [
    "index.md",
    "getting_started.md",
    "skill.md",
    "ai_and_llms.md",
    "user_guide/01_browsing_projects.md",
    "user_guide/02_schemas_and_templates.md",
    "user_guide/03_creating_metadata.md",
    "user_guide/04_retrieving_metadata.md",
    "user_guide/05_updating_metadata.md",
    "user_guide/06_working_with_formats.md",
    "user_guide/07_ai_powered_generation.md",
    "user_guide/08_managing_collections.md",
    "user_guide/09_managing_resources.md",
    "user_guide/10_deleting_data.md",
    "user_guide/11_advanced.md",
    "user_guide/12_managing_admin_metadata.md",
    "user_guide/13_users_and_permissions.md",
    "how_to/move_projects_between_collections.md",
    "how_to/batch_upload_from_excel.md",
    "how_to/instance_to_instance_migration.md",
    "reference/output_modes.md",
    "reference/metadata_types.md",
    "reference/error_handling.md",
    "reference/schemas/document.md",
    "reference/schemas/geospatial.md",
    "reference/schemas/image.md",
    "reference/schemas/indicator.md",
    "reference/schemas/indicators_db.md",
    "reference/schemas/microdata.md",
    "reference/schemas/resource.md",
    "reference/schemas/script.md",
    "reference/schemas/table.md",
    "reference/schemas/video.md",
    "developer/architecture.md",
    "developer/modules/interface.md",
    "developer/modules/requester.md",
    "developer/modules/templates.md",
    "developer/modules/llm_helpers.md",
    "developer/modules/utils.md",
    "examples.md",
    "using_automated_metadata_creation.md",
]


def _doc_url(relative_path: str) -> str:
    """Return a GitHub URL that serves the raw markdown for a docs/ path."""
    return f"{GITHUB_DOCS_BASE}/{relative_path}"


def build_llms_txt() -> None:
    """Write ``llms.txt`` at the repo root and in ``docs/`` so MkDocs serves it at /llms.txt."""
    parts: list[str] = [LLMS_TXT_INTRO.rstrip(), ""]
    for heading, entries in LLMS_TXT_SECTIONS:
        parts.append(f"## {heading}")
        parts.append("")
        for relative_path, description in entries:
            parts.append(f"- [{relative_path}]({_doc_url(relative_path)}): {description}")
        parts.append("")
    body = "\n".join(parts).rstrip() + "\n"
    (REPO_ROOT / "llms.txt").write_text(body, encoding="utf-8")
    (DOCS_ROOT / "llms.txt").write_text(body, encoding="utf-8")


def build_llms_full_txt() -> None:
    """Write ``llms-full.txt`` at the repo root and in ``docs/`` — one big concatenation of the docs."""
    header = (
        "# pyMetadataEditor — Full Documentation Bundle\n\n"
        "This file is a single-shot ingestion target for LLM consumers. It concatenates every\n"
        "user-facing documentation page in reading order, separated by file markers of the form\n"
        "``===== docs/<path> =====`` so tooling can split it back into individual documents.\n"
        "Regenerate it by running ``python make_docs.py``.\n\n"
    )
    chunks: list[str] = [header]
    for relative_path in LLMS_FULL_ORDER:
        path = DOCS_ROOT / relative_path
        if not path.exists():
            continue
        chunks.append(f"===== docs/{relative_path} =====\n\n")
        chunks.append(path.read_text(encoding="utf-8").rstrip() + "\n\n")
    body = "".join(chunks).rstrip() + "\n"
    (REPO_ROOT / "llms-full.txt").write_text(body, encoding="utf-8")
    (DOCS_ROOT / "llms-full.txt").write_text(body, encoding="utf-8")


# # Filter out cells with warnings
# for cell in notebook.cells:
#     if cell.cell_type == "code":
#         cell.outputs = [output for output in cell.get("outputs", []) if output.get("name") != "stderr"]
# filtered_cells = notebook.cells


def extract_first_elements(soup, num_elements):
    """Extracts the first `num_elements` elements from a BeautifulSoup object, with handling for tables and styles.

    Args:
        soup (BeautifulSoup or Tag or NavigableString): The BeautifulSoup object or tag to extract elements from.
        num_elements (int): The number of elements to extract.

    Returns:
        str: A string representation of the first `num_elements` elements,
             with tables truncated to 3 rows and styles excluded. If `soup`
             does not have contents, returns the string representation of `soup`.
    """
    elements = []
    count = 0
    if not hasattr(soup, "contents"):
        return str(soup)
    for element in soup.contents:
        if count >= num_elements:
            elements += "..."
            break
        if isinstance(element, str) and element.strip() == "":
            continue
        elif element.name == "style":
            continue
        elif element.name == "table":
            # truncate the table to 3 rows
            rows = element.find_all("tr")
            for row in rows[5:]:
                row.decompose()
        # if isinstance(element, str):
        #     continue
        # if hasattr(element, 'children'):
        #     s = ""
        #     for i, elem in enumerate(element.children):
        #         if i >= num_elements:
        #             s += "..."
        #             break

        #         s += extract_first_elements(elem, num_elements)
        #     elements.append(s)
        # else:
        elements.append(str(element))
        count += 1
    return "".join(elements)


# Filter out cells with warnings and truncate long outputs
def simplify_notebook_outputs(notebook):
    """Simplifies the outputs of code cells in a Jupyter notebook.

    This function processes each cell in the provided notebook and modifies the outputs of code cells by:
    - Removing the 'traceback' key from the output, keeping only the last entry if it exists.
    - Truncating the 'text/plain' data to a maximum of 300 characters, appending '...' if truncated.
    - Simplifying the 'text/html' data by extracting the first 100 elements.

    Args:
        notebook (nbformat.NotebookNode): The Jupyter notebook object to be simplified.

    Returns:
        nbformat.NotebookNode: The simplified Jupyter notebook object.
    """
    for cell in notebook.cells:
        if cell.cell_type == "code":
            new_outputs = []
            for output in cell.get("outputs", []):
                if output.get("name") != "stderr":
                    # remove the 'traceback' key from the output
                    if "traceback" in output:
                        output["traceback"] = [output["traceback"][-1]]
                    if (
                        "data" in output
                        and isinstance(output["data"], dict)
                        and "text/plain" in output["data"]
                        and len(output["data"]["text/plain"]) > 300
                    ):
                        output["data"]["text/plain"] = output["data"]["text/plain"][:300].strip() + "..."
                    if "data" in output and isinstance(output["data"], dict) and "text/html" in output["data"]:
                        soup = BeautifulSoup(output["data"]["text/html"], "html.parser")
                        output["data"]["text/html"] = extract_first_elements(next(soup.children), 100)
                    new_outputs.append(output)
            cell.outputs = new_outputs
    filtered_cells = notebook.cells

    notebook.cells = filtered_cells

    return notebook


if __name__ == "__main__":
    """Convert notebooks in demo/ to markdown and regenerate llms.txt / llms-full.txt."""
    # list every file in the demo folder ending in .ipynb, using os
    filenames = [f for f in os.listdir("demo") if f.endswith(".ipynb")]
    # exclude the file extension
    filenames = [f.split(".")[0] for f in filenames]
    for filename in filenames:
        # Load the notebook
        with open(f"demo/{filename}.ipynb") as f:
            notebook = nbformat.read(f, as_version=4)

        simplify_notebook_outputs(notebook)

        # Create a Markdown exporter
        markdown_exporter = MarkdownExporter()

        # Convert the notebook to Markdown
        (body, resources) = markdown_exporter.from_notebook_node(notebook)

        # Save the Markdown to a file
        with open(f"docs/{filename}.md", "w") as f:
            f.write(body)

    build_llms_txt()
    build_llms_full_txt()
